language: c
sudo: required
compiler:
  - clang
  - gcc
  
before_install:
  # gcc4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # clang 3.4
  -  sudo add-apt-repository -y ppa:h-rayflood/llvm;

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - sudo apt-get install -qq gcc-4.8; fi

  # clang 3.4
  - sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  
  - make
